language: python
python:
- '3.6'
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: HEQK281eta5a+/KlMvVg0OyR/x2hKXZCPknq2cyN5zgO7f6W7U5Y+KoRyTQngG0//7jhc0LNa4xhVbSZsASSpJcfXyNV0dLyiwjc/OKr6b6+k3WdoBbEm+/NYjfbjXGIFY/F7y+9U1I56OMsME2DgmqFaKbYrt0gUjYmH2C39i2rGK2UyHnENvQa6MjqhYunCB7OPd0GWiYvOW80x9kBDHyt6Mo5HkGRSA+7r72MGzBSy2vC7ERimhaJiJd2ANPUoXV83Y+dFsfx9Gu8O5BXzbbtfcJAc+mQTstWSRdvMwZVDVy6VDgxJKMuwad04GpDqxKIGD9J/9oAXR1rFFot5o7YVF0sgGWH/N3AO52zYzVsITbF7dcnRKjtCzoUsdwhWxJS2dex+Al2YrJ9mKKbSwtObumHkmBMi4WMOcEH8QubYAFVoWHMTLRXQbTS4qyVsgAmgPDvD1xX/lClnnU5SZmE8vB3TEP0eNELSumh7rd0/2C64oL2nJqLEPraquiUHWur/TOvF3fcSw8F35R8sKhw0/mGc71vhB5qwKD9drpQ/RqolBW35y7THfpYU4zxmxX+o1Ob2ZmF7ZVZhdxLPr+TronfH0TgJdkg1+c70bK6ZH/6/EH7DQMTVYm1vlOQoIkCcLpSqofCrxDOl6ShweLQd4X02M4lYBY/B2TlMKo=
  - secure: PXWINJweskD5uD1TGo9U6WTpaKhYbNf/q5ZIr/XcqYJq4WE6Urd76CPEvzg3EMTSbREGHnPF2sxXeK0O7/jRVLbI2uPGQGQm+sCKfNCdj0ILZm7nqX012fE27Xohst0OuUuyQSRQ8G4BEUleTIfeVBt4Vl1PKaAhLK03i4k+4CKP3AxNhmC7VAE27lT6dcacktg/IbvsISJbLTqX3QIY/xGYyPVLoLsLYBB07vD+2AacqRCp//d3XettyJjAkhYnXvGtDELabfUmWAmsVbuMjPiitRSWwDW7QbAUCkGU9PZruPMIwGkgRqKMStVma2JPgXju4r4Y38mo5wZbNQOOCi0EeDWtp4gC3UHphlIZjBqbIsLGFSpG8CRrmHupM2vt2XbZ9fmbydUQiDbs7pUGcTlwld82UqQW0KbHwt9XyRqNcpjxVDASlWVDSlxYDgDggS2pUHuX8Jk40IfrR1riS0U/ozRNNxlg5FGy4lwyVXO6D/ZkeMHVu1/UAnui8wPKfNeb/3IpGFfizmTqe2mwWlK5Va5xHH/mfRbYy4yUlf8dz2DkokYUo9yb4QWj0iSrJyrKwd7W8II9LrH/Utl6dHVZSih3Afb/z5+ePj5ytbQeFWnr8pUA32NKG33wfPqmjk5/BC3PASakjmyXyu3JueY6vFNghfO2aMqankcLOlA=
  - secure: JtWkaO8ZV2w46KTtbFwovjcfpgr5lISnzzqkTl+AxII5EuLlJ+dnmeXRoYwWs108PsWWjLfgfbf+oP+bxoX99eka++NPQEYeMSLQJNyjMpglKQaBsen5YJRFODqm+aalF92ln4ytrSJQJg0iTnyBtUN3BXp+wnndbnapuIv/FFTd2KliOoep1OD2QI1hy0u2qnZFTgMYcTAz1A38G8utNxzOZ6Y+QAn9ZrKWZgH+pm2h8sfSOv+wPaRXeklvsURnJgvIivjeEys3IDQC4Vs5WADV5uH7nbnmQMU7u3buXOR6YYj2wWCJR5CnLPQXAlVgTBqKMmTwJxM/EQqaiHLMcgY/F0HTMdaKsdR6qCV/qX9ioeEqMGDCNTFyDQw8wJn3j37zVVeiNu64cEMHZpRtYTxVGla3B7Ziflp+YogQVpMyyxqn2y9wsqqRTyz3ufs8OIrbRRVocGOCVzqHr4smwQnYWG+L0rDOlV/CFqOpQbgjjxtKPG6wU2NP1E87o737TKaDKE8SzZ3rYkmpAf2N5NtEogg6q4dNxODphxuyVF68E3igoWh0YOvi4lk6NsZzpuVXnAFRt4O/XFMQFH6y4mI7Fjin0gXaGf/Zd3Vt8YqAstzDIyxRrjbWIkgiZhpor/qUSqUnXSVbJ58XOlmJJ9O23ar1Egt14yK+v/qTwEA=
jobs:
  include:
  - stage: Test
    script:
    - pip install -r requirements-dev.txt
    - PYTHONPATH=./lambdas/ pytest
  - stage: Deploy
    if: branch = envs AND type = push
    script:
    - pip install awscli
    - "./deploy.sh --email=$EMAIL --stage=$TRAVIS_BRANCH"
